// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quizer_backend.Data;

namespace quizer_backend.Migrations
{
    [DbContext(typeof(QuizerContext))]
    [Migration("20181020193749_RemoveUnnessesaryProps")]
    partial class RemoveUnnessesaryProps
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("quizer_backend.Data.Entities.QuizItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedTime");

                    b.Property<long>("LastModifiedTime");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("OwnerId");

                    b.HasKey("Id");

                    b.ToTable("QuizItems");
                });

            modelBuilder.Entity("quizer_backend.Data.Entities.QuizQuestionAnswerItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCorrect");

                    b.Property<long>("LastModifiedTime");

                    b.Property<long?>("QuizQuestionItemId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionItemId");

                    b.ToTable("QuizQuestionAnswerItems");
                });

            modelBuilder.Entity("quizer_backend.Data.Entities.QuizQuestionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("LastModifiedTime");

                    b.Property<long?>("QuizItemId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("QuizItemId");

                    b.ToTable("QuizQuestionItems");
                });

            modelBuilder.Entity("quizer_backend.Data.Entities.QuizQuestionAnswerItem", b =>
                {
                    b.HasOne("quizer_backend.Data.Entities.QuizQuestionItem")
                        .WithMany("Answers")
                        .HasForeignKey("QuizQuestionItemId");
                });

            modelBuilder.Entity("quizer_backend.Data.Entities.QuizQuestionItem", b =>
                {
                    b.HasOne("quizer_backend.Data.Entities.QuizItem")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
