// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using quizer_backend.Data;

namespace quizer_backend.Migrations {
    [DbContext(typeof(QuizerContext))]
    [Migration("20181020172257_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("quizer_backend.Models.QuizItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedTime");

                    b.Property<long>("LastModifiedTime");

                    b.Property<string>("Name");

                    b.Property<long>("OwnerId");

                    b.HasKey("Id");

                    b.ToTable("QuizItems");
                });

            modelBuilder.Entity("quizer_backend.Models.QuizQuestionAnswerItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsCorrect");

                    b.Property<long>("LastModifiedTime");

                    b.Property<long>("QuizQuestionId");

                    b.Property<long?>("QuizQuestionItemId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionItemId");

                    b.ToTable("QuizQuestionAnswerItems");
                });

            modelBuilder.Entity("quizer_backend.Models.QuizQuestionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("LastModifiedTime");

                    b.Property<long>("QuizId");

                    b.Property<long?>("QuizItemId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("QuizItemId");

                    b.ToTable("QuizQuestionItems");
                });

            modelBuilder.Entity("quizer_backend.Models.QuizQuestionAnswerItem", b =>
                {
                    b.HasOne("quizer_backend.Models.QuizQuestionItem")
                        .WithMany("Answers")
                        .HasForeignKey("QuizQuestionItemId");
                });

            modelBuilder.Entity("quizer_backend.Models.QuizQuestionItem", b =>
                {
                    b.HasOne("quizer_backend.Models.QuizItem")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
